### ISSUE TITLE
MiFlora not updating

### ISSUE THREAD

**Issue by jolsso** [fison67/mi_connector#40]
Hi
I've had the MiFlora working for some weeks, but about 1-2 months ago, the sensors are not updating in the app. From the management port (i.e. raspberry:30000), I can see that the link to smartthings is working properly (using "test").

The new values are updated in the app, when I restart the docker container.

When I download the app, I get the following log:

```
2019-07-11 11:25:47 [Mi-Connector] info: Bluetooth - Mi Flora scan
2019-07-11 11:26:08 [Mi-Connector] error: (node:23) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout.setTimeout [as _onTimeout] (/usr/src/app/node_modules/miflora/lib/miflora-device.js:23:20)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
2019-07-11 11:26:08 [Mi-Connector] error: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3126)
2019-07-11 11:26:08 [Mi-Connector] error: (node:23) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout.setTimeout [as _onTimeout] (/usr/src/app/node_modules/miflora/lib/miflora-device.js:23:20)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
2019-07-11 11:26:08 [Mi-Connector] error: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3127)
2019-07-11 11:26:08 [Mi-Connector] error: (node:23) UnhandledPromiseRejectionWarning: Error: timeout
    at Timeout.setTimeout [as _onTimeout] (/usr/src/app/node_modules/miflora/lib/miflora-device.js:23:20)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)
2019-07-11 11:26:08 [Mi-Connector] error: (node:23) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3128)
2019-07-11 11:26:16 [Mi-Connector] info: Bluetooth - Mi Temperature scan

```

**Comment by fison67** [comment]
Try this version fison67/mi-connector:test2.

I've changed the way to get data from bluetooth device.

**Comment by jolsso** [comment]
Hi
The new version is working. It's polling every minute though (not every hour). Is there a mismatch between seconds and minutes?

**Comment by fison67** [comment]
It's operated by broadcasting to mi connector from bluetooth devices.
Not polling.

MI connector push it to ST per 1 min.

**Comment by jolsso** [comment]
Hm. It looks as if it's only updating the first time I reboot the Docker application. Should I delete config files between version upgrades or something else?
