### ISSUE TITLE
Cannot control every device

### ISSUE THREAD

**Issue by bubykung** [fison67/mi_connector#46]
I can see only status of device but cannot control it. I try uninstall everything and install again and problem still unsolved. I can control device through openhab normal.

Thank you for your help

**Comment by bubykung** [comment]
Now I can control some device. For device that cannot control , It looks like command not send to mi connector because I don't see any command in logs after press on/off button but if I press on/off through openhab I can see status of light in smartthings.

**Comment by bubykung** [comment]
Now is just xiaomi celing light cannot control

**Comment by fison67** [comment]
Update a smartapp & DTH.
Select a right ip on docker web setting page.

**Comment by bubykung** [comment]
I already update everything and I already select ip in docker web setting. I can control some device (xiaomi light) , just ceiling light that cannot control. command sent to smartthings but smartthings can not send to mi connector.

**Comment by fison67** [comment]
I have no idea.

**Comment by bubykung** [comment]
OK ,Thank you. I just let you know maybe there are some bugs.

**Comment by bubykung** [comment]
Updated with docker log when I try to turn on xiaomi ceiling light 1 and 5 ( same error log)

2019-12-12 04:28:54 [] error: Control >> Error!!! TypeError: Cannot read property 'target' of undefined
Error
    at router.post (/usr/src/app/routes/control.js:12:54)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at isAuthenticated (/usr/src/app/routes/dashboard.js:21:12)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7

**Comment by bubykung** [comment]
Updated : still cannot control after update latest mi connector smartapp

**Comment by bubykung** [comment]
Now I try uninstall everything and format raspberry and install everything again. Still cannot control Yeelink light ceiling 1 and 5.

**Comment by bubykung** [comment]
Update to latest Mi connector API Server 0.0.5.1 but still cannot control Yeelink light Ceiling 1 and 5.
Please Help
