### ISSUE TITLE
Cannot add Xiaomi Wall Switch to Smartthings

### ISSUE THREAD

**Issue by wixtron89** [fison67/mi_connector#59]
When I select that device and click “Register”, it pops up a dialog box with “undefined”
It only happen with Xiaomi Wall Swith single and double with no neutral line. 

Configuration:
Rpi docker mi-connector-arm: v.0.0.4
mi-connector-apps: v.0.0.46
Xiaomi Wall Switcth DTH: v.0.0.1
Mi-Hub: version 2

Log:
info | Try to register device to ST >> id=158d00031df4b6, type=lumi.ctrl_neutral2 [18/32]

warn | ST Smartapps couldn't add this id=158d00031df4b6, type=lumi.ctrl_neutral2!!!

error | Get Device State TypeError: deviceMap[id].target.state is not a function Error at Object.module.exports.getDeviceState (/usr/src/app/miio/miio.js:1487:55) at /usr/src/app/routes/registerST.js:20:10 at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13) at isAuthenticated (/usr/src/app/routes/dashboard.js:21:12) at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13) at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at /usr/src/app/node_modules/express/lib/router/index.js:281:22 at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12) at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10) at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3) at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)

error | Get Device Total State TypeError: deviceMap[id].target.state is not a function Error at Object.module.exports.getDeviceTotalState (/usr/src/app/miio/miio.js:1470:61) at /usr/src/app/routes/devices.js:48:10 at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13) at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3) at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at /usr/src/app/node_modules/express/lib/router/index.js:281:22 at param (/usr/src/app/node_modules/express/lib/router/index.js:354:14) at param (/usr/src/app/node_modules/express/lib/router/index.js:365:14) at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:410:3) at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10) at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3) at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12) at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13) at /usr/src/app/node_modules/express/lib/router/index.js:284:7

**Comment by bobdivx** [comment]
+1

**Comment by fison67** [comment]
It's a bug --> it pops up a dialog box with “undefined”.

Use a 0.0.6 docker image.
Set a auto mode. ( you don't need to register a device to st manually ) 

If it occur again let me know it
